package com.github.alexthe666.alexsmobs.misc;

import com.github.alexthe666.alexsmobs.AlexsMobs;
import com.github.alexthe666.alexsmobs.item.ItemAMInternal;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.NonNullList;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

/**
 * Creative tab display order aligned with 1.20.1: spawn eggs first ({@code initSpawnEggs()} runs before
 * other item registration), then drops/tools/blocks.
 */
public final class AMCreativeTabOrder {

    /** Same order as {@code AMItemRegistry.initSpawnEggs()} in 1.20; missing entries are skipped. */
    private static final String[] SPAWN_EGG_ORDER = {
            "spawn_egg_grizzly_bear",
            "spawn_egg_roadrunner",
            "spawn_egg_bone_serpent",
            "spawn_egg_gazelle",
            "spawn_egg_crocodile",
            "spawn_egg_fly",
            "spawn_egg_hummingbird",
            "spawn_egg_orca",
            "spawn_egg_sunbird",
            "spawn_egg_gorilla",
            "spawn_egg_crimson_mosquito",
            "spawn_egg_rattlesnake",
            "spawn_egg_endergrade",
            "spawn_egg_hammerhead_shark",
            "spawn_egg_lobster",
            "spawn_egg_komodo_dragon",
            "spawn_egg_capuchin_monkey",
            "spawn_egg_centipede",
            "spawn_egg_warped_toad",
            "spawn_egg_moose",
            "spawn_egg_mimicube",
            "spawn_egg_raccoon",
            "spawn_egg_blobfish",
            "spawn_egg_seal",
            "spawn_egg_cockroach",
            "spawn_egg_shoebill",
            "spawn_egg_elephant",
            "spawn_egg_soul_vulture",
            "spawn_egg_snow_leopard",
            "spawn_egg_spectre",
            "spawn_egg_crow",
            "spawn_egg_alligator_snapping_turtle",
            "spawn_egg_mungus",
            "spawn_egg_mantis_shrimp",
            "spawn_egg_guster",
            "spawn_egg_warped_mosco",
            "spawn_egg_straddler",
            "spawn_egg_stradpole",
            "spawn_egg_emu",
            "spawn_egg_platypus",
            "spawn_egg_dropbear",
            "spawn_egg_tasmanian_devil",
            "spawn_egg_kangaroo",
            "spawn_egg_cachalot_whale",
            "spawn_egg_leafcutter_ant",
            "spawn_egg_enderiophage",
            "spawn_egg_bald_eagle",
            "spawn_egg_tiger",
            "spawn_egg_tarantula_hawk",
            "spawn_egg_void_worm",
            "spawn_egg_frilled_shark",
            "spawn_egg_mimic_octopus",
            "spawn_egg_seagull",
            "spawn_egg_tusklin",
            "spawn_egg_laviathan",
            "spawn_egg_toucan",
            "spawn_egg_maned_wolf",
            "spawn_egg_anaconda",
            "spawn_egg_anteater",
            "spawn_egg_gelada_monkey",
            "spawn_egg_jerboa",
            "spawn_egg_terrapin",
            "spawn_egg_comb_jelly",
            "spawn_egg_cosmic_cod",
            "spawn_egg_bison",
            "spawn_egg_giant_squid",
            "spawn_egg_devils_hole_pupfish",
            "spawn_egg_catfish",
            "spawn_egg_flying_fish",
            "spawn_egg_rain_frog",
            "spawn_egg_potoo",
            "spawn_egg_rhinoceros",
            "spawn_egg_sugar_glider",
            "spawn_egg_skunk",
            "spawn_egg_banana_slug",
            "spawn_egg_blue_jay",
            "spawn_egg_caiman",
            "spawn_egg_triops",
    };

    private static final String[] ITEM_ORDER = {
            "animal_dictionary",
            "bear_fur",
            "roadrunner_feather",
            "roadrunner_boots",
            "lava_bottle",
            "bone_serpent_tooth",
            "gazelle_horn",
            "crocodile_scute",
            "crocodile_chestplate",
            "maggot",
            "banana",
            "banana_peel",
            "ancient_dart",
            "blood_sac",
            "mosquito_proboscis",
            "blood_sprayer",
            "rattlesnake_rattle",
            "chorus_on_a_stick",
            "shark_tooth",
            "shark_tooth_arrow",
            "lobster_tail",
            "cooked_lobster_tail",
            "lobster_bucket",
            "komodo_spit",
            "komodo_spit_bottle",
            "poison_bottle",
            "sopa_de_macaco",
            "centipede_leg",
            "centipede_leggings",
            "mosquito_larva",
            "moose_antler",
            "moose_headgear",
            "moose_ribs",
            "cooked_moose_ribs",
            "mimicream",
            "raccoon_tail",
            "frontier_cap",
            "blobfish",
            "blobfish_bucket",
            "fish_oil",
            "maraca",
            "sombrero",
            "cockroach_wing_fragment",
            "cockroach_wing",
            "cockroach_ootheca",
            "acacia_blossom",
            "hummingbird_feeder",
            "soul_heart",
            "spiked_scute",
            "spiked_turtle_shell",
            "shrimp_fried_rice",
            "guster_eye",
            "gustmaker",
            "pocket_sand",
            "warped_muscle",
            "hemolymph_sac",
            "hemolymph_blaster",
            "warped_mixture",
            "straddlite",
            "stradpole_bucket",
            "straddleboard",
            "emu_egg",
            "boiled_emu_egg",
            "emu_feather",
            "emu_leggings",
            "platypus_bucket",
            "fedora",
            "dropbear_claw",
            "kangaroo_meat",
            "cooked_kangaroo_meat",
            "kangaroo_hide",
            "kangaroo_burger",
            "ambergris",
            "cachalot_whale_tooth",
            "echolocator",
            "endolocator",
            "gongylidia",
            "capsid",
            "leafcutter_ant_pupa",
            "leafcutter_anthill",
            "leafcutter_ant_chamber",
            "enderiophage_rocket",
            "falconry_glove",
            "falconry_hood",
            "tarantula_hawk_wing_fragment",
            "tarantula_hawk_wing",
            "tarantula_hawk_elytra",
            "mysterious_worm",
            "void_worm_mandible",
            "void_worm_eye",
            "void_worm_beak",
            "dimensional_carver",
            "serrated_shark_tooth",
            "frilled_shark_bucket",
            "shield_of_the_deep",
            "mimic_octopus_bucket",
            "pigshoes",
            "straddle_helmet",
            "straddle_saddle",
            "cosmic_cod",
            "shed_snake_skin",
            "vine_lasso",
            "terrapin_bucket",
            "comb_jelly_bucket",
            "rainbow_jelly",
            "rainbow_glass",
            "cosmic_cod_bucket",
            "bison_fur",
            "bison_fur_block",
            "bison_carpet",
            "lost_tentacle",
            "squid_grapple",
            "devils_hole_pupfish_bucket",
            "small_catfish_bucket",
            "medium_catfish_bucket",
            "large_catfish_bucket",
            "raw_catfish",
            "cooked_catfish",
            "flying_fish",
            "flying_fish_boots",
            "flying_fish_bucket",
            "stink_bottle",
            "stink_ray",
            "banana_slug_slime",
            "banana_slug_slime_block",
            "crystalized_banana_slug_mucus",
            "triops_bucket",
            "music_disc_thime",
            "music_disc_daze",
    };

    private AMCreativeTabOrder() {
    }

    @SideOnly(Side.CLIENT)
    public static void fillCreativeTab(NonNullList<ItemStack> items) {
        for (String path : SPAWN_EGG_ORDER) {
            addCreativeTabStacks(path, items);
        }
        for (String path : ITEM_ORDER) {
            addCreativeTabStacks(path, items);
        }
    }

    @SideOnly(Side.CLIENT)
    private static void addCreativeTabStacks(String path, NonNullList<ItemStack> items) {
        Item item = net.minecraftforge.fml.common.registry.ForgeRegistries.ITEMS.getValue(new ResourceLocation(AlexsMobs.MODID, path));
        if (item == null || item instanceof ItemAMInternal || item.getCreativeTab() != AlexsMobs.TAB) {
            return;
        }
        item.getSubItems(AlexsMobs.TAB, items);
    }
}
